(custom-set-variables '(js2-strict-inconsistent-return-warning nil))
(custom-set-variables '(js2-strict-missing-semi-warning nil))

(setq js-indent-level 2)
(setq js2-indent-level 2)
(setq js2-basic-offset 2)

(add-hook 'js2-mode-hook (lambda ()
                           (linum-on)
                           (setq show-trailing-whitespace t)
                           (local-set-key (kbd "M-n i") 'npm-install)
                           (local-set-key (kbd "M-n n") 'npm-new)
                           (local-set-key (kbd "M-n d") 'npm-new-dependency)
                           (local-set-key (kbd "M-n e") 'npm-new-dev-dependency)
                           (local-set-key (kbd "M-n p") 'npm-publish)
                           (local-set-key (kbd "M-n b") 'npm-patch)
                           (local-set-key (kbd "M-n m") 'npm-minor)
                           (local-set-key (kbd "M-n a") 'npm-major)
                           (local-set-key (kbd "M-n t") 'npm-test)
                           (local-set-key (kbd "M-n s") 'npm-search)
                           (local-set-key (kbd "M-n v") 'npm-version)
                           ))

(add-hook 'rjsx-mode-hook (lambda ()
                           (define-key rjsx-mode-map "<" nil)
                           (define-key rjsx-mode-map (kbd "C-d") nil)
                           ))
